// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qitdjfckazpkqhhlacyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdGRqZmNrYXpwa3FoaGxhY3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDE1ODQsImV4cCI6MjA3MTI3NzU4NH0.9ReVIN2cnqMYTCwB0CKqtx1UmMrbrmi1_QylukgusRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: typeof window !== 'undefined',
    autoRefreshToken: typeof window !== 'undefined',
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    },
    fetch: async (url: RequestInfo | URL, options: RequestInit = {}) => {
      // 10초 timeout 추가 (무한 로딩 방지)
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000);

      try {
        // 기존 signal이 있으면 보존하면서 새 signal 연결
        const originalSignal = options.signal;
        if (originalSignal) {
          originalSignal.addEventListener('abort', () => controller.abort());
        }

        return await fetch(url, {
          ...options,
          signal: controller.signal,
        });
      } finally {
        clearTimeout(timeoutId);
      }
    },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});